package nettransfer.control.command;

import nettransfer.control.TransferError;
import nettransfer.control.TransferRequest;
import nettransfer.control.TransferService;
import nettransfer.control.TransferServiceException;
import nettransfer.control.TransferSnapshot;
import nettransfer.control.TransferSummary;

import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

import static nettransfer.control.TransferError.Code.INVALID_COMMAND;
import static nettransfer.control.TransferError.Code.EVIDENCE_UNAVAILABLE;
import static nettransfer.control.TransferError.Code.REQUEST_ALREADY_DISPATCHED;

/**
 * One entry point from interpreter proposals to a TransferService. No engine or
 * model client is involved here. The service remains responsible for atomically
 * reserving its active slot; a status-then-start check would introduce a race.
 */
public final class CommandDispatcher {
    private final CommandParser parser;
    private final CommandValidator validator;
    private final TransferService service;
    private final Set<UUID> dispatchedStarts = ConcurrentHashMap.newKeySet();

    public CommandDispatcher(CommandParser parser, CommandValidator validator, TransferService service) {
        this.parser = Objects.requireNonNull(parser, "parser");
        this.validator = Objects.requireNonNull(validator, "validator");
        this.service = Objects.requireNonNull(service, "service");
    }

    /** Trusted Java selection supplied by the CLI; the dispatcher does not guess transfer references. */
    public record Selection(UUID transferId, UUID runId) {
        public static Selection none() {
            return new Selection(null, null);
        }
    }

    public DispatchResult dispatch(UUID requestId, CommandProposal proposal) {
        return dispatch(requestId, proposal, Selection.none());
    }

    /**
     * requestId is generated by the caller's Java code for one logical user request.
     * Reuse it across retries. A new explicit request gets a fresh UUID. Start
     * attempts remain recorded for this dispatcher's lifetime, even on service
     * rejection/failure; retrying after such an outcome needs a new user request.
     */
    public DispatchResult dispatch(UUID requestId, CommandProposal proposal, Selection selection) {
        Objects.requireNonNull(requestId, "requestId");
        Objects.requireNonNull(proposal, "proposal");
        Objects.requireNonNull(selection, "selection");
        if (dispatchedStarts.contains(requestId)) {
            return rejected(REQUEST_ALREADY_DISPATCHED, "This request has already attempted a transfer start");
        }
        if (proposal instanceof CommandProposal.Clarification clarification) {
            return new DispatchResult.Clarification(clarification.question());
        }
        if (proposal instanceof CommandProposal.Unsupported unsupported) {
            return new DispatchResult.Unsupported(unsupported.reason());
        }
        var calls = ((CommandProposal.Calls) proposal).calls();
        if (calls.isEmpty()) {
            return new DispatchResult.Clarification("Please specify a transfer, status or explanation request");
        }
        if (calls.size() != 1) {
            return rejected(INVALID_COMMAND, "At most one proposed tool call is allowed; no calls were dispatched");
        }
        try {
            TransferCommand command = parser.parse(calls.get(0));
            if (command instanceof TransferCommand.Start start) {
                TransferRequest request = validator.validateStart(start, requestId);
                // Atomic insertion prevents concurrent/repeated model output from starting twice.
                if (!dispatchedStarts.add(requestId)) {
                    return rejected(REQUEST_ALREADY_DISPATCHED, "This request has already attempted a transfer start");
                }
                return new DispatchResult.Started(service.start(request), request.settings());
            }
            if (command instanceof TransferCommand.Status status) {
                UUID id = status.transferId() == null ? selection.transferId() : status.transferId();
                if (id == null) {
                    return new DispatchResult.Clarification("No transfer is selected; select an existing transfer ID");
                }
                return new DispatchResult.Status(service.status(id));
            }
            TransferCommand.Explain explain = (TransferCommand.Explain) command;
            validator.validateQuestion(explain.question());
            UUID id = explain.runId() == null ? selection.runId() : explain.runId();
            if (id == null) {
                return new DispatchResult.Clarification("No run is selected; select an existing run ID");
            }
            TransferSummary summary = service.summary(id);
            UUID selectedTransfer = explain.runId() == null ? selection.transferId() : null;
            if (!matchesSelectedIdentity(id, selectedTransfer, summary)) {
                return rejected(EVIDENCE_UNAVAILABLE, "The selected summary's run/transfer identity could not be verified");
            }
            return new DispatchResult.SummarySelected(summary, explain.question());
        } catch (TransferServiceException e) {
            return switch (e.error().code()) {
                case CLARIFICATION_REQUIRED -> new DispatchResult.Clarification(e.error().message());
                case UNSUPPORTED_REQUEST -> new DispatchResult.Unsupported(e.error().message());
                default -> new DispatchResult.Rejected(e.error());
            };
        }
    }

    /** Check both explicit and current/last selection without assuming runId equals transferId. */
    private boolean matchesSelectedIdentity(UUID runId, UUID selectedTransfer, TransferSummary summary) {
        if (summary == null) {
            return false;
        }
        TransferSnapshot evidence = summary.finalSnapshot();
        if (!runId.equals(evidence.runId())
                || (selectedTransfer != null && !selectedTransfer.equals(evidence.transferId()))) {
            return false;
        }
        try {
            // The service must recognize the returned transfer as the same run and provenance.
            TransferSnapshot registered = service.status(evidence.transferId());
            return registered != null
                    && evidence.transferId().equals(registered.transferId())
                    && runId.equals(registered.runId())
                    && evidence.evidenceSource() == registered.evidenceSource()
                    && Objects.equals(evidence.protocolTransferId(), registered.protocolTransferId());
        } catch (TransferServiceException exception) {
            // A summary exists, but its identity cannot be independently confirmed.
            return false;
        }
    }

    private static DispatchResult rejected(TransferError.Code code, String message) {
        return new DispatchResult.Rejected(new TransferError(code, message));
    }
}
